### ISSUE TITLE
collaborage2.0のGitLabは、サポート対象外のPostgreSQLバージョンを使用している可能性がある

### ISSUE THREAD

**Issue by arukiidou** [Fintan-contents/collaborage#27]
## 概要

- collaborage2.0のGitLabバージョンとPostgreSQLバージョンの組み合わせは、サポート対象外の可能性があります。  
  - 端的に言えば、PostgreSQLバージョンが新しすぎます。
- 推奨ラベル： https://github.com/Fintan-contents/collaborage/labels/bug

https://github.com/Fintan-contents/collaborage/blob/c93086d9314ce875bae19eba46ec9606a3439dfc/src/common/docker/ci-on-gitlab/docker-compose.yml#L58

### 懸念される影響

公式でテストされていないバージョンの組み合わせを用いたことで、想定外の不具合が生じる恐れがある
※ただし、不具合が起きると確定したわけではありません。

### 推奨される解決策

PostgreSQL14.xにダウングレードすることが推奨されます。

### Issue：調査- PG15 のサポートの追加(PostgreSQL15がまだ公式にテストされていないことを示す)

https://gitlab.com/gitlab-org/omnibus-gitlab/-/issues/8336

### docs：PostgreSQL15は、バージョン17.x(早くとも17.1以降)のオプションサポートです

https://handbook.gitlab.com/handbook/engineering/infrastructure/core-platform/data_stores/database/postgresql-upgrade-cadence/

**Comment by kumagoro1202** [comment]
ご報告ありがとうございます。
こちらのPRで対応しました。
https://github.com/Fintan-contents/collaborage/pull/32

また、横並びで確認したところRocket.chatが仕様するMongoDBについても公式で案内されているバージョンより新しいものを使用していたため合わせて対応しました。
